MATH ADVENTURES WITH PYTHON
AN ILLUSTRATED GUIDE TO EXPLORING MATH WITH CODE

INTRODUCTION

THE PROBLEM WITH SCHOOL MATH
ABOUT THIS BOOK
WHO SHOULD USE THIS BOOK
WHAT’S IN THIS BOOK?
DOWNLOADING AND INSTALLING PYTHON
STARTING IDLE
INSTALLING PROCESSING
PART I
HITCHIN’ UP YOUR PYTHON WAGON
1
DRAWING POLYGONS WITH THE TURTLE MODULE
PYTHON’S TURTLE MODULE
IMPORTING THE TURTLE MODULE
CHANGING DIRECTIONS
REPEATING CODE WITH LOOPS
USING THE FOR LOOP
CREATING SHORTCUTS WITH FUNCTIONS
USING VARIABLES TO DRAW SHAPES
USING VARIABLES IN FUNCTIONS
VARIABLE ERRORS
EQUILATERAL TRIANGLES
WRITING THE TRIANGLE() FUNCTION
MAKING VARIABLES VARY
SUMMARY

2
MAKING TEDIOUS ARITHMETIC FUN WITH LISTS AND
LOOPS

